### ISSUE TITLE
deploy.py fails on running migrations while deploying v2021.2-100-g760f7d81

### ISSUE THREAD

**Issue by henningkessler** [zentralopensource/zentral#338]
Hello,

I am trying to deploy the current main branch (v2021.2-100-g760f7d81) to my ZAIO in GCP running `sudo /home/zentral/app/utils/deploy.py`. The process fails while running migrations with this error:
```
psycopg2.errors.UniqueViolation: could not create unique index "one_open_incident_per_incident_type_and_key"
DETAIL:  Key (incident_type, key)=(probe, {"probe_pk": 0}) is duplicated.
```
more verbose:
```
...
Operations to perform:
  Apply all migrations: accounts, auth, authtoken, contenttypes, django_celery_results, filebeat, incidents, invent
ory, munki, osquery, probes, realms, santa, sessions
Running migrations:
  Applying incidents.0002_auto_20211201_1224...Traceback (most recent call last):
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: could not create unique index "one_open_incident_per_incident_type_and_key"
DETAIL:  Key (incident_type, key)=(probe, {"probe_pk": 0}) is duplicated.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/zentral/app/releases/2021.12.15-06.55.32-github.com-zentralopensource-zentral-main-v2021.2-100-g760f7
d81/server/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execut
e_from_command_line
    utility.execute()
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execut
e
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_a
rgv
    self.execute(*args, **cmd_options)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, i
n handle
    post_migrate_state = executor.migrate(
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate
_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_mi
gration
    state = migration.apply(state, schema_editor)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/db/migrations/operations/models.py", line 827, in
 database_forwards
    schema_editor.add_constraint(model, self.constraint)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 345, in add_con
straint
    self.execute(sql)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_
wrappers
    return executor(sql, params, many, context)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/zentral/app/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: could not create unique index "one_open_incident_per_incident_type_and_key"
DETAIL:  Key (incident_type, key)=(probe, {"probe_pk": 0}) is duplicated.
Found 39407 MAC assignments. Use --update to update.
```

**Comment by np5** [comment]
It looks like you have incidents in your DB pointing to probes that do not exist anymore. This is blocking the migration. Can you connect to the DB:

```
sudo -u zentral \
  ZENTRAL_CONF_DIR=/home/zentral/conf/ \
  /home/zentral/app/venv/bin/python \
  /home/zentral/app/releases/current/server/manage.py \
  dbshell
```

 and run this query:


```
select count(*) from incidents_incident where probe_source_id is null;
```

**Comment by henningkessler** [comment]
result is:
```
zentral=> select count(*) from incidents_incident where probe_source_id is null;
 count 
-------
     3
(1 row)
```

**Comment by np5** [comment]
Yes. You need to delete the `incidents_machineincident` connected to them beforehand, if they are any.

**Comment by np5** [comment]
Something like:

```
select incident_id, count(*) from incidents_machineincident where incident_id in (select id from incidents_incident where probe_source_id is null) group by incident_id;
```

And if you are confident that you are not deleting to much data:

```
delete from incidents_machineincident where incident_id in (select id from incidents_incident where probe_source_id is null);
```

**Comment by henningkessler** [comment]
```delete from incidents_machineincident where incident_id in (select id from incidents_incident where probe_source_id is null);```
```delete from incidents_incident where probe_source_id is null;```
Issue Solved :-)
