### ISSUE TITLE
export in zentral targets not working

### ISSUE THREAD

**Issue by henningkessler** [zentralopensource/zentral#377]
Hello, 

I am trying to export the targets of Santa in Zentral as ZIP or XLS but nothing happens

this in on ZAIO on GCP with Zentral version v2021.2-182-gcd809483

here is the output of `journalctl -r`:
```
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]: 2022-03-07 12:49:31,126 PID1631825 glogging INFO 127.0.0.1 - - [07/Mar/2022:12:49:31 +0000] "POST /api/santa/targets/export/?export_format=zip HTTP/1.0" 500 >
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]: ModuleNotFoundError: No module named 'django-db'
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     module = imp(module_name, package=package, **kwargs)
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     cls = symbol_by_name(backend, aliases)
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/celery/app/backends.py", line 50, in by_name
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     return by_name(backend, loader), url
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/celery/app/backends.py", line 70, in by_url
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     backend, url = backends.by_url(
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/celery/app/base.py", line 955, in _get_backend
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     self._local.backend = new_backend = self._get_backend()
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/celery/app/base.py", line 1252, in backend
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     self.backend.on_task_call(P, task_id)
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/celery/app/base.py", line 787, in send_task
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     return app.send_task(
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/celery/app/task.py", line 575, in apply_async
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     result = export_targets.apply_async((query, target_type, filename))
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/releases/2022.03.07-12.40.21-github.com-zentralopensource-zentral-main-v2021.2-182-gcd809483/zentral/contrib/santa/api_views.py", l>
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     response = handler(request, *args, **kwargs)
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     raise exc
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     self.raise_uncaught_exception(exc)
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     response = self.handle_exception(exc)
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     return self.dispatch(request, *args, **kwargs)
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     return view_func(*args, **kwargs)
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     return func(*args, **kwds)
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     response = self.process_exception_by_middleware(e, request)
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     response = get_response(request)
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]: Traceback (most recent call last):
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]: During handling of the above exception, another exception occurred:
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]: AttributeError: '_thread._local' object has no attribute 'backend'
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:     return self._local.backend
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]:   File "/home/zentral/app/venv/lib/python3.8/site-packages/celery/app/base.py", line 1250, in backend
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]: Traceback (most recent call last):
Mar 07 12:49:31 zentral.buddybrand.de gunicorn[1631825]: 2022-03-07 12:49:31,123 PID1631825 log ERROR Internal Server Error: /api/santa/targets/export/
```

**Comment by np5** [comment]
Was the virtualenv in /home/zentral/app/venv also updated ? It looks like the `django-celery-results` dependency is not correctly loaded.

**Comment by henningkessler** [comment]
All I did for updating was to use the python script:
```sudo /home/zentral/app/utils/deploy.py```

**Comment by np5** [comment]
Could you run the following command, please:

```
sudo -u zentral ZENTRAL_CONF_DIR=/home/zentral/conf/ /home/zentral/app/venv/bin/python /home/zentral/app/releases/current/server/manage.py shell -c 'from django_celery_results import VERSION;print(VERSION)'
```

It should display `version_info_t(major=2, minor=2, micro=0, releaselevel='', serial='')`

You could also try to restart the `zentral_web_app.service`.

**Comment by henningkessler** [comment]
It does display exact that
```it@zentral:~$ sudo -u zentral ZENTRAL_CONF_DIR=/home/zentral/conf/ /home/zentral/app/venv/bin/python /home/zentral/app/releases/current/server/manage.py shell -c 'from django_celery_results import VERSION;print(VERSION)'
version_info_t(major=2, minor=2, micro=0, releaselevel='', serial='')```
and restart `zentral_web_app.service` did indeed solved the issue :-)
