### ISSUE TITLE
Errors running "docker run -t -i -v /opt/my-zentral-conf:/home/zentral/conf zentral/zentral check"

### ISSUE THREAD

**Issue by goobersmooch** [zentralopensource/zentral#4]
I'm having trouble with part 3 of the installation tutorial https://github.com/zentralopensource/docs/blob/master/zentral-docker-tutorial_3.md.

I've followed the zentral-docker-tutorial instructions exactly up to this point, but when i run "docker run -t -i -v /opt/my-zentral-conf:/home/zentral/conf zentral/zentral check" as instructed I always get the following errors:

Traceback (most recent call last):
  File "/zentral/docker-entrypoint.py", line 83, in <module>
    os.execvp(filename, args)
  File "/usr/local/lib/python3.4/os.py", line 525, in execvp
    _execvpe(file, args)
  File "/usr/local/lib/python3.4/os.py", line 570, in _execvpe
    raise last_exc.with_traceback(tb)
  File "/usr/local/lib/python3.4/os.py", line 560, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by goobersmooch** [comment]
I have found a solution thanks to jbaker and henry.  Henry said "So if you do a pull of "https://github.com/zentralopensource/zentral" onto your server, you can change into that directory and run `docker-compose up -d`. That will set everything up for you".

Be sure to modify zentral/conf/start/zentral/base.json to suit your environment first.
