### ISSUE TITLE
Issues with Santa Enrollment Package. With or without installer. 

### ISSUE THREAD

**Issue by mm-johnpeterson** [zentralopensource/zentral#72]
When I create the Santa enrollment package I am presented with the following error (running on Google all-in-one)

`Traceback (most recent call last):
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/zentral/app/releases/2018.12.09-01.54.47-master-fead3d/zentral/contrib/santa/views.py", line 165, in post
    cp_name, cp_content = build_configuration_profile(enrolled_machine)
  File "/home/zentral/app/releases/2018.12.09-01.54.47-master-fead3d/zentral/contrib/santa/utils.py", line 49, in build_configuration_profile
    content = sign_payload_openssl(plistlib.dumps(configuration_profile_data))
  File "/home/zentral/app/releases/2018.12.09-01.54.47-master-fead3d/zentral/utils/payloads.py", line 23, in sign_payload_openssl
    "-inkey", api_settings["tls_server_key"],
KeyError: 'tls_server_key'`

I have updated to the latest version and installed all requirements. I verified the /var/db/santa/config.plist has been created and the ServerAuthRootsFile, MachineID, ClientMode and SyncBaseUrl have all been populated. The package installs without error but the post install sync never kicks off and if I run it manually I get the Missing SyncBaseURL error. 

Fwiw am also using the Munki and osquery packages and those build and enroll clients without issue.

**Comment by np5** [comment]
You need to check in the `api` section of the configuration (`base.json`) that you have a `base_url` key with the path of the private key corresponding to the tls certificate as value. The key is used to sign the [configuration profile for the santa configuration](https://santa.readthedocs.io/en/latest/deployment/configuration/). We do not touch the ` /var/db/santa/config.plist` anymore.

**Comment by mm-johnpeterson** [comment]
@np5 thanks for the response. Just to make sure I understand that correctly, because it looks odd when I configure it.
`  "api": {
    "secret": "longAPIsecret",
    "base_url": "/etc/letsencrypt/archive/zentral.mycompany.com/privkey1.pem",
    "tls_server_certs": "/home/zentral/conf/zentral.mycompany.com_fullchain.pem",
    "tls_hostname": "https://zentral.mycompany.com"
  },`

I set up using lets encrypt, and the only private keys I can find are the ones in the /etc/letsencrypt directory. But looking at this the base_url would be the value of tls_hostname no?

**Comment by mm-johnpeterson** [comment]
That fixed my problem. Thank you for your help!
