### ISSUE TITLE
Issue with api_urls after updating

### ISSUE THREAD

**Issue by johnnyramos** [zentralopensource/zentral#75]
Seems like the latest update to zentral breaks it:

After running `sudo /home/zentral/app/utils/deploy.py --update`, it sets all the requirements successfully but then gives the following errors.

After reloading the service, the UI no longer comes on.

Errors:
```
2019-03-21 02:42:40,048 PID21931 urls ERROR Could not load app munki api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.42.36-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.munki.api_urls'
2019-03-21 02:42:40,075 PID21931 urls ERROR Could not load app osquery api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.42.36-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.osquery.api_urls'
2019-03-21 02:42:40,083 PID21931 urls ERROR Could not load app jamf api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.42.36-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.jamf.api_urls'
2019-03-21 02:42:40,168 PID21931 urls ERROR Could not load app santa api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.42.36-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.santa.api_urls'
2019-03-21 02:42:40,171 PID21931 urls ERROR Could not load app nagios api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.42.36-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.nagios.api_urls'
2019-03-21 02:42:40,172 PID21931 urls ERROR Could not load app probes api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.42.36-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.core.probes.api_urls'
Operations to perform:
  Apply all migrations: accounts, auth, authtoken, contenttypes, inventory, jamf, munki, nagios, osquery, probes, santa, sessions
Running migrations:
  No migrations to apply.
2019-03-21 02:42:41,284 PID21938 urls ERROR Could not load app santa api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.42.36-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.santa.api_urls'
2019-03-21 02:42:41,286 PID21938 urls ERROR Could not load app munki api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.42.36-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.munki.api_urls'
2019-03-21 02:42:41,294 PID21938 urls ERROR Could not load app osquery api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.42.36-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.osquery.api_urls'
2019-03-21 02:42:41,298 PID21938 urls ERROR Could not load app jamf api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.42.36-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.jamf.api_urls'
2019-03-21 02:42:41,298 PID21938 urls ERROR Could not load app probes api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.42.36-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.core.probes.api_urls'
2019-03-21 02:42:41,300 PID21938 urls ERROR Could not load app nagios api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.42.36-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.nagios.api_urls'
```

**Comment by np5** [comment]
The ImportError on the api_urls modules should not be a problem. It just means that there are no API endpoints for a given package (munki, santa, …). They should be silent (and there have been silenced in the drilldown branch).

There are probably other errors in the logs, if the UI is not displayed.

**Comment by np5** [comment]
The fix to silence the api_urls.py errors is in the master branch now. We have updated the "Zentral all in one" AWS AMIs and GCP image too.

Did you manage to get more information from the logs and fix your issue ?

**Comment by johnnyramos** [comment]
All is good now.
