### ISSUE TITLE
error running deploy.py on AWS AMI

### ISSUE THREAD

**Issue by zacharysfisher** [zentralopensource/zentral#76]
I get following errors when running deploy:

`2019-03-21 02:51:24,202 PID14585 urls ERROR Could not load app probes api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.51.19-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.core.probes.api_urls'
2019-03-21 02:51:24,333 PID14585 urls ERROR Could not load app osquery api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.51.19-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.osquery.api_urls'
2019-03-21 02:51:24,338 PID14585 urls ERROR Could not load app munki api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.51.19-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.munki.api_urls'
2019-03-21 02:51:24,341 PID14585 urls ERROR Could not load app nagios api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.51.19-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.nagios.api_urls'
2019-03-21 02:51:24,345 PID14585 urls ERROR Could not load app jamf api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.51.19-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.jamf.api_urls'
2019-03-21 02:51:24,357 PID14585 urls ERROR Could not load app santa api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.51.19-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.santa.api_urls'
Operations to perform:
  Apply all migrations: accounts, auth, authtoken, contenttypes, inventory, jamf, munki, nagios, osquery, probes, santa, sessions
Running migrations:
  No migrations to apply.
2019-03-21 02:51:25,776 PID14593 urls ERROR Could not load app santa api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.51.19-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.santa.api_urls'
2019-03-21 02:51:25,778 PID14593 urls ERROR Could not load app jamf api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.51.19-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.jamf.api_urls'
2019-03-21 02:51:25,781 PID14593 urls ERROR Could not load app probes api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.51.19-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.core.probes.api_urls'
2019-03-21 02:51:25,783 PID14593 urls ERROR Could not load app munki api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.51.19-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.munki.api_urls'
2019-03-21 02:51:25,866 PID14593 urls ERROR Could not load app osquery api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.51.19-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.osquery.api_urls'
2019-03-21 02:51:25,868 PID14593 urls ERROR Could not load app nagios api_urls
Traceback (most recent call last):
  File "/home/zentral/app/releases/2019.03.21-02.51.19-master-8f21ee/server/server/urls.py", line 36, in <module>
    include(url_module, namespace=namespace)))
  File "/home/zentral/app/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'zentral.contrib.nagios.api_urls'
Found 31719 MAC assignments. Use --update to update`

Any ideas?

**Comment by zacharysfisher** [comment]
Not sure if it is related but seeing this

`sudo systemctl status zentral_web_app
● zentral_web_app.service - Zentral Web App
   Loaded: loaded (/etc/systemd/system/zentral_web_app.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-03-20 22:05:17 UTC; 4h 49min ago
  Process: 14603 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 3796 (gunicorn)
    Tasks: 5
   Memory: 266.7M
      CPU: 3min 57.168s
   CGroup: /system.slice/zentral_web_app.service
           ├─ 3796 /home/zentral/app/venv/bin/python3.5 /home/zentral/app/venv/bin/gunicorn --chdir /home/zentral/app/releases/current/server -b 0.0.0.0:8000 -w 4 --access-logfile - --error-logfile -
           ├─14613 /home/zentral/app/venv/bin/python3.5 /home/zentral/app/venv/bin/gunicorn --chdir /home/zentral/app/releases/current/server -b 0.0.0.0:8000 -w 4 --access-logfile - --error-logfile -
           ├─14614 /home/zentral/app/venv/bin/python3.5 /home/zentral/app/venv/bin/gunicorn --chdir /home/zentral/app/releases/current/server -b 0.0.0.0:8000 -w 4 --access-logfile - --error-logfile -
           ├─14615 /home/zentral/app/venv/bin/python3.5 /home/zentral/app/venv/bin/gunicorn --chdir /home/zentral/app/releases/current/server -b 0.0.0.0:8000 -w 4 --access-logfile - --error-logfile -
           └─14616 /home/zentral/app/venv/bin/python3.5 /home/zentral/app/venv/bin/gunicorn --chdir /home/zentral/app/releases/current/server -b 0.0.0.0:8000 -w 4 --access-logfile - --error-logfile -

Mar 21 02:54:13 zentral.intersection.com gunicorn[3796]: 2019-03-21 02:54:13,726 PID14613 api ERROR APIAuthError Wrong node_key
Mar 21 02:54:13 zentral.intersection.com gunicorn[3796]: 2019-03-21 02:54:13,726 PID14613 api_views ERROR APIAuthError Wrong node_key
Mar 21 02:54:16 zentral.intersection.com gunicorn[3796]: 2019-03-21 02:54:16,731 PID14613 api ERROR APIAuthError Wrong node_key
Mar 21 02:54:16 zentral.intersection.com gunicorn[3796]: 2019-03-21 02:54:16,731 PID14613 api_views ERROR APIAuthError Wrong node_key
Mar 21 02:54:18 zentral.intersection.com gunicorn[3796]: 2019-03-21 02:54:18,288 PID14615 api ERROR APIAuthError Wrong node_key
Mar 21 02:54:18 zentral.intersection.com gunicorn[3796]: 2019-03-21 02:54:18,288 PID14615 api_views ERROR APIAuthError Wrong node_key
Mar 21 02:54:22 zentral.intersection.com gunicorn[3796]: 2019-03-21 02:54:22,960 PID14616 api ERROR APIAuthError Wrong node_key
Mar 21 02:54:22 zentral.intersection.com gunicorn[3796]: 2019-03-21 02:54:22,960 PID14616 api_views ERROR APIAuthError Wrong node_key
Mar 21 02:54:27 zentral.intersection.com gunicorn[3796]: 2019-03-21 02:54:27,620 PID14615 api ERROR APIAuthError Wrong node_key
Mar 21 02:54:27 zentral.intersection.com gunicorn[3796]: 2019-03-21 02:54:27,620 PID14615 api_views ERROR APIAuthError Wrong node_key`

As well as in Prometheus it says zentral_inventory is down

**Comment by np5** [comment]
The import errors for the API urls are not critical. They have been silenced in the `drilldown` branch. We will merge this branch soon in the `master` branch.

The `ERROR APIAuthError Wrong node_key` indicate that an osquery client doesn't have the correct key to authenticate with the Zentral server.

What kind of inventory sources have you configured for your zentral inventory worker ? If you want to see the workers errors, use something like `journalctl -u zentral_workers.service`

**Comment by zacharysfisher** [comment]
Quick update seemed that running `sudo apt-get upgrade -y` broke the inventory section and prevented me from successfully enrolling.  I rolled back the server and now I do not see that error and in Prometheus, everything is up.  thanks for the help!
