### ISSUE TITLE
Elasticsearch pip dependencies break?

### ISSUE THREAD

**Issue by juju4** [zentralopensource/zentral#93]
Since past week, my zentral ansible role broke
https://travis-ci.org/juju4/ansible-zentral/jobs/640849157#L5084
```
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]: 2020-01-25 06:19:05,310 PID25669 sync INFO Waiting for notifications on channel 'probe_change'
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]: 2020-01-25 06:19:05,505 PID25672 sync INFO Waiting for notifications on channel 'probe_change'
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]: 2020-01-25 06:19:05,625 PID25670 workers INFO inventory worker dummy??- sleep 30 seconds
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]: 2020-01-25 06:19:05,937 PID25673 elasticsearch INFO Index zentral-events created
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]: Process store worker elasticsearch:
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]: Traceback (most recent call last):
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:     self.run()
[...]
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:   File "/usr/local/lib/python3.6/dist-packages/kombu/messaging.py", line 624, in _receive_callback
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:     return on_m(message) if on_m else self.receive(decoded, message)
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:   File "/usr/local/lib/python3.6/dist-packages/kombu/messaging.py", line 590, in receive
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:     [callback(body, message) for callback in callbacks]
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:   File "/usr/local/lib/python3.6/dist-packages/kombu/messaging.py", line 590, in <listcomp>
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:     [callback(body, message) for callback in callbacks]
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:   File "/var/_zentral/zentral/zentral/core/queues/backends/kombu.py", line 244, in do_store_event
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:     self.event_store.store(body)
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:   File "/var/_zentral/zentral/zentral/core/stores/backends/elasticsearch.py", line 214, in store
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:     self.wait_and_configure_if_necessary()
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:   File "/var/_zentral/zentral/zentral/core/stores/backends/base.py", line 12, in wait_and_configure_if_necessary
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:     self.wait_and_configure()
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:   File "/var/_zentral/zentral/zentral/core/stores/backends/elasticsearch.py", line 156, in wait_and_configure
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:     recovery = self._es.indices.get(self.index, feature="_recovery")
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]:     return func(*args, params=params, **kwargs)
       Jan 25 06:19:05 default-ubuntu-1804-1579932397 zentral[25528]: TypeError: get() got an unexpected keyword argument 'feature'
```

No change in zentral from commit history but in elasticsearch as 7.5.1 got out since Jan 18th
https://pypi.org/project/elasticsearch/#history

role execution back to normal if forcing 7.1

**Comment by np5** [comment]
Thank you very much!
