### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by Rico358097990** [zentralopensource/zentral#94]
I have some question on setup
```Configure elasticsearch
Traceback (most recent call last):
  File "/home/zentral/app/venv/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/zentral/app/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/zentral/app/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zentral/app/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/zentral/app/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/zentral/app/venv/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/zentral/app/venv/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fbb48a90518>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zentral/app/venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/zentral/app/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zentral/app/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /_ilm/policy/zentral-events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbb48a90518>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zentral/app/utils/setup.py", line 697, in <module>
    args.local_email_delivery)
  File "/home/zentral/app/utils/setup.py", line 633, in setup
    configure_elasticsearch()
  File "/home/zentral/app/utils/setup.py", line 336, in configure_elasticsearch
    response = session.get("{}_ilm/policy/{}".format(api_base_url, lifecycle_policy_id))
  File "/home/zentral/app/venv/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/zentral/app/venv/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zentral/app/venv/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/zentral/app/venv/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /_ilm/policy/zentral-events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbb48a90518>: Failed to establish a new connection: [Errno 111] Connection refused',))```

**Comment by np5** [comment]
It is not really a question!

It looks like you are running the application on a "Zentral all in one" image, and that the application cannot connect to elasticsearch.

Did you change anything in the configuration ?

**Comment by Rico358097990** [comment]
I did not change any configuration，I just follow your YouTube video

**Comment by np5** [comment]
Which one ?

Is elasticsearch up ?

**Comment by Rico358097990** [comment]
NO，I don't think elasticsearch is up
the vidio link is https://www.youtube.com/watch?v=oH2kz3JOgzs

**Comment by np5** [comment]
… can you start elasticsearch ?
